POST http://localhost:3333/polls
content-type: application/json

{
  "title": "qual seu livro de programação favorito?",
  "pollOptions": ["DDD", "Clean code", "Entendendo algoritmos"]
}
###
GET  http://localhost:3333/polls/18dbf72b-a9ca-4f8e-9bef-06e48b8f1822

### 
POST http://localhost:3333/polls/18dbf72b-a9ca-4f8e-9bef-06e48b8f1822/vote
content-type: application/json

{
  "pollOptionId": "03ffcde7-1a05-44af-8b21-8026bd090919"
}
