POST http://localhost:3333/polls
content-type: application/json

{
  "title": "qual é sua linguagem de programação favorita?",
  "pollOptions": ["javaScript", "C#", "Go"]
}
###
GET  http://localhost:3333/polls/7690c458-6c2e-43a4-9c0a-ad191641140d

### 
POST http://localhost:3333/polls/7690c458-6c2e-43a4-9c0a-ad191641140d/vote
content-type: application/json

{
  "pollOptionId": "46c1ee5f-7bc5-4243-b539-20aad5754105"
}
###
GET  http://localhost:3333/polls/d7cbaaa3-524e-4b21-ac50-bb448bd622c1/result