POST http://localhost:3333/polls
content-type: application/json

{
  "title": "qual é sua linguagem de programação favorita?",
  "pollOptions": ["javaScript", "C#", "Go"]
}
###
GET  http://localhost:3333/polls/d7cbaaa3-524e-4b21-ac50-bb448bd622c1


### 
POST http://localhost:3333/polls/d7cbaaa3-524e-4b21-ac50-bb448bd622c1/vote
content-type: application/json

{
  "pollOptionId": "53fd69c8-78b8-4963-a328-3e0ddc118bcc"
}